version: '3.5'
services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    environment:
      POSTGRES_DB: users-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always

  app:
    build: .
    container_name: application
    ports:
     - 9000:9000
    environment:
      NODE_ENV: compose
      PORT: 9000
      DATABASE_URI: postgres://root:password@postgres:5432/users-db
      CACHE_URI: redis://redis:6379/
    command: ['./scripts/wait-for-it.sh', 'postgres:5432', '--strict', '--', 'npm', 'run', 'compose']
    depends_on:
      - postgres
      - redis

  seeder:
    build:
      context: .
      dockerfile: Dockerfile.seeder
    container_name: seeder
    command: ['npx sequelize-cli db:seed:all --url postgres://root:password@postgres:5432/users-db']
    depends_on:
      - app
